# Generated by Django 5.1.2 on 2024-11-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='language',
            field=models.CharField(choices=[('python', 'Python3'), ('cpp', 'C++20')], default='python', max_length=20),
        ),
    ]
