# Generated by Django 5.1.2 on 2024-11-11 18:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_solution_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='statement_az',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Statement in Azerbaijani', max_length=400),
        ),
        migrations.AddField(
            model_name='problem',
            name='statement_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Statement in English', max_length=400),
        ),
    ]
