# Generated by Django 5.1.2 on 2024-11-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_statement_az_problem_statement_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='title_az',
            field=models.CharField(blank=True, help_text='Azerbaycan dilinde basliq', max_length=60),
        ),
        migrations.AddField(
            model_name='problem',
            name='title_en',
            field=models.CharField(blank=True, help_text='Title in Engish', max_length=60),
        ),
    ]
