# Generated by Django 5.1.2 on 2024-11-11 20:05

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_title_az_problem_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement_az',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Statement in Azerbaijani', max_length=1000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Statement in English', max_length=1000),
        ),
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Ornegin giris verisi')),
                ('output_data', models.TextField(help_text='Ornegin cikis verisi')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ornekler', to='problems.problem')),
            ],
        ),
    ]
