# Generated by Django 5.1.2 on 2024-12-02 19:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_problem_statement_alter_problem_statement_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examples',
            name='input_data',
            field=ckeditor.fields.RichTextField(help_text='Ornegin giris verisi'),
        ),
        migrations.AlterField(
            model_name='examples',
            name='output_data',
            field=ckeditor.fields.RichTextField(help_text='Ornegin cikis verisi'),
        ),
    ]
