# Generated by Django 5.1.2 on 2024-12-03 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_solution_result_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 1, 12, 0)),
        ),
    ]
