# Generated by Django 5.1.2 on 2024-12-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_solution_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
