# Generated by Django 5.1.2 on 2024-10-28 14:11

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_join_date',
            field=models.DateTimeField(default=users.models.one_minute_ago),
        ),
    ]
