# Generated by Django 5.1.2 on 2024-10-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_first_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_join_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
