# Generated by Django 5.1.2 on 2024-12-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='solved_problem_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
