# Generated by Django 5.1.2 on 2024-10-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRCodersTrying', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Taslak olussunmu?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='icerik',
            field=models.TextField(verbose_name='Icerik'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Baslik'),
        ),
    ]
