# Generated by Django 5.1.2 on 2024-10-25 18:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRCodersTrying', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='icerik',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Fotgraf ekle'),
        ),
    ]
