from django.urls import path

from.views import *

urlpatterns = [
    path('all',all_geoups,name="all_groups"),
    path('all/mobile',all_geoups_mobile,name="all_groups_mobile"),
    path('detail/<int:pk>/',group_detail,name='group_detail'),
    path('detail/<int:pk>/mobile',group_detail_mobile,name='group_detail_mobile'),
    path('members/<int:group_id>/',members,name="members"),
    path('members/<int:group_id>/mobile',members_mobile,name="members_mobile"),
    path('lessons/<int:group_id>/',all_lessons,name="lessons"),
    path('lessons/<int:group_id>/mobile',all_lessons_mobile,name="lessons_mobile"),
    path('group/<int:group_id>/lesson/<int:lesson_id>/',lesson_detail,name="lesson_detail"),
    path('group/<int:group_id>/lesson/<int:lesson_id>/mobile',lesson_detail_mobile,name="lesson_detail_mobile"),
    path('group/<int:group_id>/lesson/<int:lesson_id>/tasks',lesson_tasks,name="lesson_tasks"),
    path('group/<int:group_id>/lesson/<int:lesson_id>/tasks/mobile',lesson_tasks_mobile,name="lesson_tasks_mobile"),
    path('group/<int:group_id>/lesson/<int:lesson_id>/tasks/<int:task_id>/',task_detail,name="task_detail"),
    path('group/<int:group_id>/lesson/<int:lesson_id>/tasks/<int:task_id>/mobile',task_detail_mobile,name="task_detail_mobile"),
    path('group/<int:group_id>/lesson/<int:lesson_id>/tasks/submit/<int:task_id>',task_submit_solution,name="task_submit_solution"),
    path('group/<int:group_id>/lesson/<int:lesson_id>/tasks/submit/<int:task_id>/mobile',task_submit_solution_mobile,name="task_submit_solution_mobile"),
    path('group/<int:group_id>/lesson/<int:lesson_id>/tasks/<int:solution_id>/solution/',task_solution_result,name="task_solution_result"),
    path('group/<int:group_id>/lesson/<int:lesson_id>/tasks/<int:solution_id>/solution/mobile',task_solution_result_mobile,name="task_solution_result_mobile"),
    path('group/<int:group_id>/lesson/<int:lesson_id>/leaderboard/',leaderboard,name="leaderboard"),
    path('group/<int:group_id>/lesson/<int:lesson_id>/leaderboard/mobile',leaderboard_mobile,name="leaderboard_mobile"),
    path('create', create_group_step1, name='create_group'),
    path('create/mobile', create_group_step1_mobile, name='create_group_mobile'),
    path('search-users/', search_users, name='search_users'),
    path('create/<int:group_id>/add_members', create_group_step2, name='create_group_step2'),
    path('create/<int:group_id>/add_members/mobile', create_group_step2_mobile, name='create_group_step2_mobile'),
    path('group/<int:group_id>/settings/main',group_setting_main,name="settings"),
    path('group/<int:group_id>/settings/main/mobile',group_setting_main_mobile,name="settings_mobile"),
    path('group/<int:group_id>/settings/members',group_setting_members,name="member_management"),
    path('group/<int:group_id>/settings/members/mobile',group_setting_members_mobile,name="member_management_mobile"),
    path('add-search-users/',search_users_while_group,name="add-search-users"),
    path('group/<int:group_id>/settings/members/add',group_add_members,name="add_members"),
    path('group/<int:group_id>/settings/members/add/mobile',group_add_members_mobile,name="add_members_mobile"),
    path('group/<int:group_id>/lesson/create',create_lesson,name="create_lesson"),
    path('group/<int:group_id>/lesson/create/mobile',create_lesson_mobile,name="create_lesson_mobile"),
    path('group/<int:group_id>/lesson/<int:lesson_id>/problems/add',add_problems_to_lesson,name="add_problems"),
    path('group/<int:group_id>/lesson/<int:lesson_id>/problems/add/mobile',add_problems_to_lesson_mobile,name="add_problems_mobile"),
    path('search/group/<int:group_id>/lesson/<int:lesson_id>/problems/', search_problems, name='search_problems'),
    path('group/<int:group_id>/lesson/<int:lesson_id>/settings', lesson_settings, name='lesson_settings'),
    path('group/<int:group_id>/lesson/<int:lesson_id>/settings/mobile', lesson_settings_mobile, name='lesson_settings_mobile'),
    path('group/<int:group_id>/lesson/<int:lesson_id>/settings/problems', lesson_task_settings, name='lesson_task_settings'),
    path('group/<int:group_id>/lesson/<int:lesson_id>/settings/problems/mobile', lesson_task_settings_mobile, name='lesson_task_settings_mobile'),
    path('group/<int:group_id>/leave',group_leave, name='group_leave'),
    path('group/<int:group_id>/delete',group_delete, name='group_delete'),
]