# Generated by Django 5.1.2 on 2024-12-08 19:06

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_group_created_by_group_admin_group_members_and_more'),
        ('problems', '0011_alter_solution_created_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='GroupLessonProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.IntegerField(default=100)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_lesson', to='groups.lesson')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_lesson_problems', to='problems.problem')),
            ],
        ),
        migrations.CreateModel(
            name='GroupLessonSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text='Kullanıcının kodu')),
                ('language', models.CharField(choices=[('python', 'Python3'), ('cpp', 'C++20')], default='python', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('result_value', models.CharField(blank=True, max_length=15)),
                ('all_results', models.JSONField(blank=True, default=list, help_text='Test sonuçlarının doğru/yanlış bilgisi')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_lesson_solutions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
