# Generated by Django 5.1.2 on 2024-12-08 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_admin_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplessonproblem',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_of_lesson', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='grouplessonsolution',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_lesson_solutions', to='groups.grouplessonproblem'),
        ),
        migrations.DeleteModel(
            name='LessonResult',
        ),
    ]
