# Generated by Django 5.1.2 on 2024-12-08 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_grouplessonproblem_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplessonsolution',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='problem_of_lesson', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='grouplessonsolution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_lesson_solutions', to='groups.grouplessonproblem'),
        ),
    ]
