# Generated by Django 5.1.2 on 2024-12-09 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_grouplessonsolution_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='problems',
        ),
        migrations.AddField(
            model_name='grouplessonsolution',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pol', to='groups.lesson'),
        ),
    ]
