# Generated by Django 5.1.2 on 2024-12-10 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_alter_lessonuserproblemstatus_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonuserproblemstatus',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status_problem_of_lesson', to='groups.group'),
        ),
        migrations.AddField(
            model_name='lessonuserproblemstatus',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status_pol', to='groups.lesson'),
        ),
    ]
